import pino from 'pino';
import { env } from './env';

export const logger = pino({
  level: env.NODE_ENV === 'test' ? 'silent' : env.NODE_ENV === 'production' ? 'info' : 'debug',
  redact: {
    paths: [
      'req.headers.authorization',
      'req.headers.cookie',
      'req.headers["x-guest-token"]',
      'password',
      'passwordHash',
      'token',
      'accessToken',
      'refreshToken',
      'resetToken',
      'tokenHash',
      'resetTokenHash',
      'guestAccessTokenHash',
      'secret',
      'apiKey',
      'apiSecret',
      'clientSecret',
      'smtpPassword',
      'cloudinaryApiSecret',
      'cloudinarySignature',
      'signature',
      'paymentProofUrl',
      'paymentProof',
      'paymentDetails',
      'cardNumber',
      'cvv',
      'address',
      'fullAddress',
      'customerNotes',
      'notes',
      'authorization',
      'cookie',
      'mongoUri',
      'mongodbUri',
      'MONGODB_URI',
      '*.password',
      '*.passwordHash',
      '*.token',
      '*.accessToken',
      '*.refreshToken',
      '*.resetToken',
      '*.secret',
      '*.apiKey',
      '*.apiSecret',
      '*.clientSecret',
      '*.smtpPassword',
      '*.cloudinaryApiSecret',
      '*.signature',
      '*.paymentProofUrl',
      '*.paymentDetails',
      '*.customerNotes',
      '*.cardNumber',
      '*.cvv',
      '*.authorization',
      '*.cookie',
    ],
    censor: '[REDACTED]',
  },
  transport:
    env.NODE_ENV !== 'production'
      ? {
          target: 'pino-pretty',
          options: {
            colorize: true,
            translateTime: 'SYS:standard',
            ignore: 'pid,hostname',
          },
        }
      : undefined,
});
